# Generated by Django 4.2.27 on 2026-01-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('sales_channel', models.CharField(max_length=50)),
                ('order_priority', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('ship_date', models.DateField()),
                ('units_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
